
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- HYPRLAND CONFIG                                        --
-- Split into modules alongside this file. See the wiki:  --
-- https://wiki.hypr.land/Configuring/Start/               --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- hl.config({ autogenerated = true }) -- remove this line to remove the warning

require("monitors")
require("autostart")
require("env")
require("permissions")
require("look")
require("layouts")
require("misc")
require("input")
require("keybinds")
require("windowrules")
